<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit616ac152d78627ea4a4fd96704bbe6e9
{
    public static $prefixLengthsPsr4 = array (
        'a' => 
        array (
            'app\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'app\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/www/app',
        ),
    );

    public static $prefixesPsr0 = array (
        'a' => 
        array (
            'abeautifulsite' => 
            array (
                0 => __DIR__ . '/..' . '/abeautifulsite/simpleimage/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit616ac152d78627ea4a4fd96704bbe6e9::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit616ac152d78627ea4a4fd96704bbe6e9::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit616ac152d78627ea4a4fd96704bbe6e9::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
